import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { FileSystemRepository } from "../adapter/filesystem-repository.js";

export async function replayCommand(opts: {
  output?: string;
  from?: number;
  to?: number;
}): Promise<void> {
  const repo = FileSystemRepository.create();
  const steps = await repo.listSteps();

  if (steps.length === 0) {
    console.log(
      "ステップがありません。`intent collect` で収集してください。"
    );
    return;
  }

  const from = opts.from ?? 1;
  const to = opts.to ?? steps[steps.length - 1].number;

  const filtered = steps.filter(
    (s) => s.number >= from && s.number <= to
  );

  if (filtered.length === 0) {
    console.log(`ステップ ${from}-${to} の範囲にステップが見つかりません。`);
    return;
  }

  const lines: string[] = [
    `# Intent Replay: Step ${String(from).padStart(3, "0")}-${String(to).padStart(3, "0")}`,
    "",
    `> Generated by \`intent replay\` on ${new Date().toISOString().slice(0, 10)}`,
    "",
    "---",
    "",
  ];

  for (const step of filtered) {
    const num = String(step.number).padStart(3, "0");
    const tags = step.tags.length > 0 ? ` [${step.tags.join(", ")}]` : "";

    lines.push(`## Step ${num}: ${step.title}${tags}`);
    lines.push("");

    if (step.prompt) {
      lines.push("### Prompt");
      lines.push("");
      lines.push("```");
      lines.push(step.prompt);
      lines.push("```");
      lines.push("");
    }

    if (step.reasoning) {
      lines.push(`**Reasoning**: ${step.reasoning}`);
      lines.push("");
    }

    if (step.outcome) {
      lines.push(`**Outcome**: ${step.outcome}`);
      lines.push("");
    }

    if (step.friction) {
      lines.push(`**Friction**: ${step.friction}`);
      lines.push("");
    }

    if (step.relatedSteps.length > 0) {
      const related = step.relatedSteps.map((n) => `Step ${String(n).padStart(3, "0")}`).join(", ");
      lines.push(`**Related**: ${related}`);
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  const content = lines.join("\n");

  if (opts.output) {
    const outPath = resolve(opts.output);
    writeFileSync(outPath, content, "utf-8");
    console.log(`${filtered.length}個のステップを ${outPath} に出力しました。`);
  } else {
    console.log(content);
  }
}
